PENDING: remoteproc: k3-common: release rproc control before suspend
If the rproc (DM) control is not released before suspend, TFA will fail
at resume:
Enabling non-boot CPUs ...
ERROR:   Timeout waiting for thread RX_SECURE_TRANSPORT_CHANNEL_ID to fill
ERROR:   Thread RX_SECURE_TRANSPORT_CHANNEL_ID verification failed (-60)
ERROR:   Message receive failed (-60)
ERROR:   Failed to get response (-60)
ERROR:   Transfer send failed (-60)
ERROR:   Request to start core failed: -60

So, we need to release the control at suspend and request them back at
resume.

Signed-off-by: Richard Genoud (TI) <richard.genoud@bootlin.com>